name: quartet
description: Quartet is a huge collection of useful string manipulation functions written in the Dart language.
homepage: https://github.com/hexrcs/quartet_dart
version: 0.1.1

dev_dependencies:
  test: ^1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
